wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1722275891.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 98
      - 105
      3:
      - 23
      4: 3.9.18
      5: 0.16.4
      6: 4.38.2
      8:
      - 2
      - 5
      13: linux-x86_64
